### ISSUE TITLE
Paginering på kartsidan

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#10]
Paginering fungerar bra på "Event" sidan. På kartsidan fungerar den bra om man klickar på siffrorna, men använder jag pilen verkar den göra en GET till `http://localhost:3000/events` och skriver ut fler siffror än vad det finns sidor. 

En annan förbättring man skulle kunna göra är att ha en fast storlek på fönstret "senaste eventen" så att inte pagineringen flyttar på sig varje gång man klickar.

**Comment by olafranzen** [comment]
Fixat dels nästa o föregående-knapparna på kartsidan samt "disabling" av nästa/föregående-knapparna istället för att dölja dem när de inte ska kunna användas för att pagineringen inte ska flytta på sig.
