### ISSUE TITLE
Filtrering av events

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#11]
Om man går in på listan över alla event går det väldigt smidigt och snabbt att söka på namn, plats eller tagg. Om jag har förstått det rätt hämtar den alla events och lagrar dem i sessionstorage så att de finns till nästa gång. Det är en bra lösning men jag funderar på hur det fungerar om det finns hundratals event. 

En annan lösning är att låta api:et sköta filteringen så att inte alla events hämtas ut på en gång. Jag ser också att det finns möjlighet att skicka med parametrar som `name_starts_with`, men det verkar inte som att du använder dem?

**Comment by olafranzen** [comment]
Kartsidan använder redan api:ets inbyggda möjlighet till att paginera resultatet (dvs endast ladda en del åt gången och bara visa dessa). På events-sidan fick jag ladda in alla då det görs filtrering direkt i angular på alla event (gör att eventen inte behöver laddas varje gång man skriver i ny bokstav i filteringen t.ex). Dock inte testat för större antal events men bör flyta på ganska bra ihop med cachningen.
