### ISSUE TITLE
Går inte att radera event

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#12]
När jag klickar på knappen "Ja, ta bort eventet" händer det ingenting. I web inspectors console skrivs det ut `Cannot set property 'center' of undefined`. Det verkar ske en PUT när det borde ske en DELETE. Om jag går in på sidan "Ändra event" för det eventet visas felmeddelande "Kunde inte spara, åtgärda felet och spara igen."

**Comment by olafranzen** [comment]
Fixat, hade av någon anledning missat att färdigställa implementationen av detta.
