### ISSUE TITLE
Felmeddelande i formulär dröjer kvar

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#13]
Om jag skriver in ett felaktigt värde i formuläret för att skapa nytt eller redigera event visas felmeddelande på ett bra sätt. Men om jag går in på en annan sida utan att spara är felmeddelandet krav om jag går in på formuläret igen.

**Comment by olafranzen** [comment]
Fixat, hade missat att återställa felmeddelanden vid laddning av controllern/sidan.
