### ISSUE TITLE
Datum när eventet inträffar

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#14]
Önskar att jag kunde sätta ett datum när eventet tar plats. Ett krav på api:et var att det skulle sorteras på datum. Jag tolkade det som att det var det datum som eventet sker, men det kanske är det datum när eventet skapades så som du har.

**Comment by olafranzen** [comment]
Absolut en bra poäng och möjlighet till förbättring. Har dock kört på skapande-datum för sorteringen som jag hoppas täcker det kravet.
