### ISSUE TITLE
Sammanfattning

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#15]
Sammanfattningsvis kan man säga att vi har gjort på lite olika sätt. Medan jag låter api:et sköta sådant som paginering, sökning, osv låter du klienten hantera det. Fördelen med att göra på ditt sätt är att det går snabbare och smidigare. Nackdelen är att man måste hämta alla events ur databasen på en gång. Eftersom du cachar datat är det inte ett lika stort problem dock. 

Andra saker som är väldigt bra är: 
- Trevligt sätt att lägga till och ta bort taggar. 
- Bra felhantering. 
- Undviker dry genom att ha samma formulär för edit och update. 
- Bra struktur med services som sköter kontakt med api:et och localstorage. 
- Bra sätt att lägga till koordinater genom att placera ut marker på kartan. 
- Korrekt syntax. 
- Bra hantering av olika användare och rättigheter. 

Det jag kan sakna är mer kommentarer och tätare commits. Men om man går efter kurshemsidan uppfyller du alla grundläggande krav och har även några extra funktioner så som cache-strategi och paginering. Bra jobbat!

**Comment by olafranzen** [comment]
Tack för en mycket bra peer review, fick en hel del nyttiga förbättringspunkter! :)
