### ISSUE TITLE
controllerAs

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#16]
Du använder controllerAs vilket gör att du får tillgång till this som du kan tilldela till variabeln vm, vilket är bra eftersom man - om jag förstått det rätt -  inte ska använda $scope i onödan. Däremot kan jag inte se att du gör det i ListController. Finns det någon anledning till det? Vad skulle hända om du tog bort controllerAs gällande den controllern?

**Comment by olafranzen** [comment]
Det stämmer, listController som anges i controllerAs för ListController används inte i template-filen. Dock kan det ändå vara bra att ha möjlighet till det. Bra poäng att försöka undvika $scope mer och använda just controllern, ska ta till mig det mer i nästa projekt. :)
