### ISSUE TITLE
Peer review #2 - Default format

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#4]
Det kan vara en bra idé att definiera ett defaultformat för anrop mot ditt API, så att användare inte behöver skriva ".json" i sitt anrop.

Detta kan du göra i dina routes. Här är ett exempel på hur du kan göra det för dina tags:

`resources :tags, only: [:index, :show], defaults: { format: :json }`

**Comment by olafranzen** [comment]
Löst genom en helper-funktion:
request.format = 'json' unless params[:format]
