### ISSUE TITLE
Peer review #2 - Allmänt

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#8]
#### Installation

Det var inga problem att få igång applikationen. Installationsguiden var bra och vagrantfilen fungerade utmärkt.

Seedsfilen var välfylld så det var lätt att testa sökning och sidindelning.
#### Körning

Jag har experimenterat med applikationen och försökt göra allt man kan men den för att hitta buggar. 

Jag fick ett problem när jag tog bort ett event, och sedan försökte hitta events nära en viss plats. Det hade med referentiell integritet att göra och det finns en tidigare issue med mer info. I övrigt fungerar allting som det ska.

Felmeddelanden och felkoder hanteras väl, exempelvis att man får 401 tillbaka när man försöker ändra fel resurs. Bra att ha två separata felmeddelanden, ett för utvecklare och ett för slutanvändare. Det är något som jag borde implementera i mitt eget API. 

Jag tycker också att lösningen för duplicerade taggar är smart, så att man antingen skapar en tagg om dess namn inte finns, eller kopplar eventet till en existerande tagg. Då slipper användaren få tillbaka ett valideringsfel om man skapar ett event med en tagg som redan finns.
#### Kodkvalitet

Jag har också kollat över koden och jag tycker att det ser bra ut. If-satser blir väldigt kompakta och lättlästa när man gör dem på en rad som [du gör här](https://github.com/of222au/1DV450-Webbramverk/blob/master/WebAPI/app/controllers/events_controller.rb#L23-L26). Har inget att klaga på gällande indentering och liknande.
#### Förslag på förbättring

Det finns några saker som jag hade gjort annorlunda. Jag har gjort en issue för varje punkt.

**Comment by olafranzen** [comment]
Sen återkoppling av mig men tack för väldetaljerad review och issues :)
