### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ghost** [of222au/1DV450-Webbramverk#9]
Att komma igång med servern gick utmärkt. Men när jag följer [instruktionerna ](https://github.com/of222au/1DV450-Webbramverk#för-att-köra-igång-klienten) för att köra klienten får jag 404 för att den letar efter resurser i `/bower_components`. Testade att köra `npm install` men det fungerade inte. Kan köra applikationen om jag istället hämtar angular.js och de andra resurserna från ett cdn eller lägger in dem manuellt.

**Comment by olafranzen** [comment]
Fixat genom att inkludera de js och css-filer som låg lokalt i /bower_components
